insert into pipeline_status values
(1,'Unset'),
(2,'Call back'),
(3,'For screening'),
(4,'Awaiting CV'),
(5,'CV for review'),
(6,'For paper screening'),
(7,'For interview'),
(8,'For exam'),
(9,'Awaiting result'),
(10,'Hired'),
(11,'For JO'),
(12,'For PEME'),
(13,'Not interested'),
(14,'Not exploring'),
(15,'Not pursuing'),
(16,'Unresponsive'),
(17,'No show'),
(18,'Not qualified'),
(19,'Failed'),
(20,'Keep profile'),
(21,'Closed');